### ISSUE TITLE
crash after npm start

### ISSUE THREAD

**Issue by RidicTinyArchive** [2Epik4u/Wrapper-Online#4]
tried running the code earlier offline with node.js installed, lets me do `npm install` but when i try `npm start`, it says 
```
> wrapper-online@1.2.0 start C:\Users\user\Downloads\Wrapper-Online-master\Wrapper-Online-master
> node main.js

```
but then goes back to the command prompt (`C:\Users\user\Downloads\Wrapper-Online-master\Wrapper-Online-master>`)

am i doing something wrong? entirely new installation. tried on a mac to no avail

**Comment by 2Epik4u** [comment]
fixed.

**Comment by RidicTinyArchive** [comment]
now i get an error for 
```
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module 'brotli'
Require stack:
- C:\Users\user\Documents\GitHub\Wrapper-Online\tts\load.js
- C:\Users\user\Documents\GitHub\Wrapper-Online\server.js
- C:\Users\user\Documents\GitHub\Wrapper-Online\main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\user\Documents\GitHub\Wrapper-Online\tts\load.js:7:16)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\user\Documents\GitHub\Wrapper-Online\server.js:23:13)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\user\\Documents\\GitHub\\Wrapper-Online\\tts\\load.js',
    'C:\\Users\\user\\Documents\\GitHub\\Wrapper-Online\\server.js',
    'C:\\Users\\user\\Documents\\GitHub\\Wrapper-Online\\main.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wrapper-online@0.0.1 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wrapper-online@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2020-10-08T22_13_48_228Z-debug.log
```

**Comment by 2Epik4u** [comment]
did you do npm install?

**Comment by RidicTinyArchive** [comment]
yes, after i did i got the result
```
npm WARN wrapper-online@0.0.1 No repository field.
npm WARN wrapper-online@0.0.1 No license field.

audited 7 packages in 2.016s
found 0 vulnerabilities

```
and then after running `npm start` it just spits out the error

**Comment by RidicTinyArchive** [comment]
gave it another shot and i'm still getting the same `Error: Cannot find module 'brotli'` error.

**Comment by 2Epik4u** [comment]
try this `sudo chown -R $USER:$(id -gn $USER) /Users/PUTUSERNAMEHERE/.config

**Comment by 2Epik4u** [comment]
I fixed it now. just get the newest version and do npm install
